# group_vars/k3s_workers.yaml
# This is stored in vault
# k3s_token: "{{ vault_k3s_token }}"

k3s_server_url: "https://10.40.30.204:6443"

# choose one:
k3s_install_channel: "stable"   # or "v1.30" / pin with k3s_install_version instead
# k3s_install_version: "v1.30.4+k3s1"

k3s_node_labels:
  - "role=worker"
  - "runner=true"

k3s_node_taints: []  # e.g. ["ci-only=true:NoSchedule"]

http_proxy:  "http://10.40.30.21:81"
https_proxy: "http://10.40.30.21:81"
no_proxy_list:
  - "127.0.0.1"
  - "localhost"
  - "10.0.0.0/8"
  - ".svc"
  - ".cluster.local"
  - "10.43.0.1"        # control-plane API
