$ANSIBLE_VAULT;1.2;AES256;prod
64613231343332666130653035656539393430353365393964616565383532393737306161303963
3138323638313339666436346230643562643934306130360a613965316266336632316330366263
39303961643332613038353862656438633064353163643432316336393836323136306465333636
6339626532393864610a393731316565346338323036633533663733303633326232303434636535
39646531393738376635396233646337363962336166633035396363613931353237643330356461
37303862393538623833666635663730383737306232346638623933353638386531383035356332
65376135393063613431623839613831373236613162336363346166613663616563333462343461
31383363343735343235626430633037383234343336343764613561613232373034386264656661
30373663643735373666633233636138303535613538643632343738383533383439643433653833
3562666233383666306539366663623366633231303561663861
