percona_mysql_version: "8.0"
percona_mysql_bind_address: "0.0.0.0"
percona_mysql_port: 3306
percona_mysql_service_enabled: true
percona_mysql_service_state: started
# systemd service name
percona_mysql_service_name: mysql

percona_mysql_datadir: /var/lib/mysql
percona_mysql_main_conf: /etc/mysql/my.cnf
percona_mysql_conf_d: /etc/mysql/conf.d

# Binary used for config validation handlers
percona_mysql_server_bin: "/usr/sbin/mysqld"

percona_mysql_user: mysql
percona_mysql_group: mysql

# switch: false => Percona Server; true => Percona XtraDB Cluster
percona_mysql_cluster: false
restart: true
