$ANSIBLE_VAULT;1.2;AES256;prod
65626534653466666230386563393463383666316539623733393332626264316430326166636561
6531386435643461633333353236653163653832373263340a376666613261666661323435393032
38396364663435316163363662613766643466383434653339616336323237326539303234313766
3265363632336638610a313833353139333862373337343465353863336162386138656564613863
64653166363066353565646631333966306264653239393362376233376639313866313730613334
30396134353831366565346439373536613133376633326139613939643765353935633830333834
31633731333062653762613866646534333832376231313363353764343336383766313365313161
64343536353239653434
